#!/usr/bin/zsh
# sanity
alias sudo='sudo ' # allow aliases in sudo
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../../"
alias .......="cd ../../../../../../"
alias ........="cd ../../../../../../../"
alias .........="cd ../../../../../../../../"
alias ..........="cd ../../../../../../../../../"
alias ...........="cd ../../../../../../../../../../"
alias ............="cd ../../../../../../../../../../../"
alias ~="cd ~"
alias l='ls'
alias ls='exa -aF --color=always --sort=type --group-directories-first --ignore-glob=".DS_Store" --icons' # lots of icons are causing lag in st
alias ll='ls -l' 
alias lt='ls --tree'
# alias cpI="cp"
# alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias bc="bc -ql"
alias mkdir="mkdir -pv"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias watch="watch --color"

# wallpaper management
alias w2="/home/carson/.local/bin/newpape2.sh"
alias rw="/home/carson/.local/bin/newpape.sh"
alias cw="/home/carson/.local/bin/choosepape.sh"
# archive current wallpaper by moving out of selection pool
function archivePape {
    mv $(sed -n '2p' ~/.fehbg | awk -F"'" '{print $4}') ~/files/photos/oldpapes
}
alias archivew="archivePape"
alias archive-w="archivePape"

# config storage
alias config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
alias cfg="config"

# comfort
alias quit="shutdown 3"
alias disconnect="exit"
alias cr="cargo run"
alias crr="cargo run --release"
alias cb="cargo build"
alias cbr="cargo build --release"
alias cf="cargo fetch"
alias rr='./run'
alias rt='./test'
alias mr="make && ./run"
alias jj='nohup java -jar'
alias smci='sudo make clean install'
alias :q='exit'
alias :wq='exit'
alias ka="killall"
alias python="python3"
alias calpoly="TERM=screen ssh ckfreedm@unix3.csc.calpoly.edu"
alias calpoly1="TERM=screen ssh ckfreedm@unix1.csc.calpoly.edu"
alias calpoly2="TERM=screen ssh ckfreedm@unix2.csc.calpoly.edu"
alias calpoly4="TERM=screen ssh ckfreedm@unix4.csc.calpoly.edu"
alias calpoly5="TERM=screen ssh ckfreedm@unix5.csc.calpoly.edu"
alias cp127="TERM=screen ssh ckfreedm@127x12.csc.calpoly.edu"
alias cpftp="sftp ckfreedm@unix3.csc.calpoly.edu"
alias fuck="sudo !!"
alias clr="clear"
alias cl="clear"

# applications, apps
alias top="htop"
alias pm="pulsemixer"
alias g="git"
alias bt="bluetuith"
alias hp="bluetuith"
alias sony="bluetuith"
alias lg="lazygit"
alias discord="LIBVA_DRIVER_NAME=i915 discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy"
alias nf="fastfetch"
alias fff="fastfetch"
# random cow and fortune
function randomCowsay {
    cowsay -W 60 -f $(cowsay -l | sed '1d' | tr ' ' '\n' | sort -R | head -1)
}
# alias ff="fastfetch && tput setaf 6; fortune -n 400 -s | randomCowsay; tput sgr0"
alias fastfetch=''
alias ff="fastfetch --load-config /home/carson/.config/fastfetch/configsm.conf && tput setaf 6; fortune -n 400 -s | randomCowsay; tput sgr0"
alias zath="zathura"
alias e="nvim"
alias v="vim"
alias se="sudoedit"
alias magit="nvim -c Neogit"
alias tt="tt -quotes en -t 30 -theme carson -showwpm -bold -noskip"
alias tt10="tt -words 1000en -n 120 -g 5 -t 60 -theme carson -showwpm -bold -noskip"
alias fastfetch='fastfetch --load-config /home/carson/.config/fastfetch/config.conf'
alias reddit="tuir"
alias doom="~/.config/emacs/bin/doom"
alias rtv="tuir"
alias vpn="protonvpn-cli"
alias ncdu="gdu"
alias pomo="pomo -p /home/carson/.config/pomo/config.json"
alias ps1="pomo -p /home/carson/.config/pomo/config.json b 1"
alias ps2="pomo -p /home/carson/.config/pomo/config.json b 2"
alias ps3="pomo -p /home/carson/.config/pomo/config.json b 3"
alias ps4="pomo -p /home/carson/.config/pomo/config.json b 4"
alias ps5="pomo -p /home/carson/.config/pomo/config.json b 5"
# alias t='tmux attach -t $(tmux ls | grep -v attached | head -1 | cut -f1 -d:) || tmux' # attach to any available session
alias t="/home/carson/.local/bin/fetchtmuxstart $1"
alias ts="/home/carson/.local/bin/fetchtmuxstart study"
alias td="/home/carson/.local/bin/fetchtmuxstart dev"
alias t0="tmux a -t 0 || tmux new"
alias t1="tmux a -t 1 || tmux new"
alias fontpreview='fontpreview-ueberzug'
alias wttr="curl wttr.in/San+Luis+Obispo"
alias wttr2="curl v2d.wttr.in/San+Luis+Obispo"
alias ccal="cal"
# alias cal="calcurse"
alias egpu="sudo egpu-switcher"
alias gpu="sudo egpu-switcher"
alias ncdu="ncdu --color dark"
alias visuals="mpv https://www.youtube.com/playlist?list=PLHz5hL1kaCdx7FfIfBWof7-p0mNwNFrRU --shuffle"
alias yts="ytfzf -t --preview-side=right --thumbnail-quality=high --notify-playing -l --pages=alias4"
alias yt="ytfzf -t --preview-side=right --thumbnail-quality=high --notify-playing -l --pages=4 -c S --sort"
alias ytsub="yt"
alias yta="ytfzf -m -t" # youtube audio
alias red='systemctl restart --user --now redshift-gtk'
alias twitchlive="reflex-curses -f"
alias ttvlive="reflex-curses -f"
alias ttvl="reflex-curses -f"
alias ttv="reflex-curses"
alias twitch="reflex-curses"
alias define="dict"
alias dic="dict"
alias tempmail="tmpmail"
alias via="sudo via --no-sandbox"
alias kanban="kabmat"
alias km="kabmat"
alias visual="/usr/local/bin/visual/VisUAL.sh"
alias fd="fd -H"

# scripts
alias dock="/home/carson/.local/bin/displays/dock.sh"
alias triple="/home/carson/.local/bin/displays/triple.sh"
alias dk="/home/carson/.local/bin/displays/dock.sh"
alias updateedm="/home/carson/.local/bin/updateplaylist.sh"
alias dlsong="/home/carson/.local/bin/dlsong.sh"

# system
alias igpu="supergfxctl -m integrated"
alias pmrestart="systemctl --user restart pipewire.service pipewire.socket pipewire-pulse.socket"
alias pwrestart="systemctl --user restart pipewire.service pipewire.socket pipewire-pulse.socket"
alias battery='acpi'
alias ctrl='setxkbmap -option ctrl:nocaps'
# alias webcam='guvcview -e --gui=none -d /dev/video0 -a none -c read -F 30 -x 1280x960'
alias playmic='pactl load-module module-loopback latency-msec=0'
alias unplaymic='pactl unload-module module-loopback'
function getBatteryDrawNow {
    printf $(awk '{print $1*10^-6 " W"}' /sys/class/power_supply/BAT0/power_now)
    printf " Watts \n"
}
alias powerdraw="getBatteryDrawNow"
alias batterydraw="getBatteryDrawNow"
alias bdraw="getBatteryDrawNow"

# pacman 
alias p='pacman' # install
alias pac='sudo pacman -S' # install
alias pacr='sudo pacman -Rs' # remove
alias pacs='pacman -Ss' # search
alias paci='pacman -Si' # info
alias paclo='pacman -Qdt' # list orphans
alias pacro='paclo && sudo pacman -Rns $(pacman -Qtdq)' # remove orphans
alias pacc='sudo pacman -Scc' # clean cache
alias paclf='pacman -Ql' # list files
alias updatemirrors="sudo reflector --country 'United States' --protocol http,https --download-timeout 60 --latest 10 --sort age --save /etc/pacman.d/mirrorlist"

# make sure everything is done writing from cache before shutting down
alias shutdown="sync && sync && sync && shutdown 0"

# go to root of git dir
alias gitroot='cd $(git rev-parse --show-toplevel)'
