#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               18
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         05
spacebar -m config padding_right        05
spacebar -m config spacing_left         10
spacebar -m config spacing_right        10
spacebar -m config text_font            "Tamzen Nerd Font:Medium:14.0"
spacebar -m config icon_font            "Tamzen Nerd Font:Medium:14.0"
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config space_icon           
spacebar -m config dnd_icon
spacebar -m config clock_format         "%a %b %d, %H:%M:%S"
spacebar -m config right_shell          off
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "whoami"

source ~/.config/spacebar/spacebarcolors
echo "spacebar configuration loaded.."
