#!/usr/bin/env sh

source ~/.cache/wal/colors.sh

cback=$(echo $background | sed 's/#//')
cfore=$(echo $foreground | sed 's/#//')
cactv=$(echo $color3 | sed 's/#//')
cnorm=$(echo $color1 | sed 's/#//')
cinse=$(echo $foreground | sed 's/#//')

sketchybar -m config bar_color 0xD8$cback
sketchybar -m default icon_color 0x5A$cfore
sketchybar -m default label_color 0x5A$cfore

echo "sketchybar: colors loaded"
