#!/usr/bin/env sh

source ~/.cache/wal/colors.sh

cback=$(echo $background | sed 's/#//')
cfore=$(echo $foreground | sed 's/#//')
cactv=$(echo $color3 | sed 's/#//')
cnorm=$(echo $color1 | sed 's/#//')
cinse=$(echo $foreground | sed 's/#//')

sketchybar -m config bar_color     0xB2$cback
sketchybar -m default icon_color 0xff$cfore
sketchybar -m default label_color 0xff$cfore

echo "sketchybar: colors loaded"
