#!/usr/bin/env sh

echo "sketchybar: loading configuration..."
# BAR SETUP
sketchybar -m --bar height=18       \
                    position=top    \
                    padding_left=5  \
                    padding_right=5 \
                    blur_radius=5   \
                    topmost=off     \
                    display=all

sketchybar -m --add event window_focus
sketchybar -m --add event title_change

# GLOBAL DEFAULTS
sketchybar -m --default cache_scripts=on \
                        drawing=on       \
                        icon.font="Tamzen Nerd Font:Medium:14.0" \
                        label.font="Tamzen Nerd Font:Medium:14.0" \

# SPACE DEFAULTS
sketchybar -m --default label.padding_left=6 \
                        label.padding_right=0 \
                        icon.padding_left=12 \
                        icon.padding_right=0 \
                        icon.highlight_color=0xfffb4934 \

# SPACES
sketchybar -m --add space one left \
              --set one associated_display=1 \
                        associated_space=1 \
                        icon=I \
                        click_script="yabai -m space --focus 1" \
                        icon_padding_left=0

sketchybar -m --add space two left \
              --set two associated_display=1 \
                        associated_space=2 \
                        icon=II \
                        click_script="yabai -m space --focus 2" \

sketchybar -m --add space three left \
              --set three associated_display=1 \
                          associated_space=3 \
                          icon=III \
                          click_script="yabai -m space --focus 3" \

sketchybar -m --add space four left \
              --set four associated_display=1 \
                         associated_space=4 \
                         icon=IV \
                         click_script="yabai -m space --focus 4" \

sketchybar -m --add space five left \
              --set five associated_display=2 \
                         associated_space=5 \
                         icon=V \
                         click_script="yabai -m space --focus 5" \

sketchybar -m --add space six left \
              --set six associated_display=2 \
                        associated_space=6 \
                        icon=VI \
                        click_script="yabai -m space --focus 6" \

################## LEFT ITEMS ##################

# Window Title
sketchybar -m --add item title left \
              --set title label.padding_left=3 \
                          icon.padding_left=0 \
                          script="~/.config/sketchybar/plugins/title.sh" \
              --subscribe title window_focus \
                                front_app_switched \
                                space_change \
                                title_change \

################# RIGHT ITEMS ####################
sketchybar -m --add item clock right \
              --set clock update_freq=1 \
                          script="~/.config/sketchybar/plugins/clock.sh" \
                          label.padding_left=2 \
                          label.padding_right=0 \
                          icon.padding_left=3 \
                          icon.padding_right=0 \
                          icon=

# Weather
# sketchybar -m add item weather right
# sketchybar -m set weather update_freq 600
# sketchybar -m set weather script "~/.config/sketchybar/plugins/weather.sh"
# sketchybar -m set weather click_script "open https://darksky.net/forecast/22.2109,-159.4081/us12/en"
# sketchybar -m set battery icon_padding_left 3

# Battery
sketchybar -m --add item battery right \
              --set battery update_freq=10 \
                            script="~/.config/sketchybar/plugins/power.sh" \
                            icon= \
                            label.padding_left=0 \
                            label.padding_right=4 \
                            icon.padding_left=0 \
                            icon.padding_right=3

# Cpu graph
# sketchybar -m add component graph cpu_user right 150 nospace
# sketchybar -m set cpu_user script "~/.config/sketchybar/plugins/cpu_graph.sh"
# sketchybar -m set cpu_user graph_color 0xffffffff
# sketchybar -m set cpu_user update_freq 5
# sketchybar -m set cpu_user associated_space 1
# sketchybar -m set cpu_user label_padding_left 8
# sketchybar -m set cpu_user icon_padding_left 8
# sketchybar -m set cpu_user icon 
#
# sketchybar -m add component graph cpu_sys right 150
# sketchybar -m set cpu_sys graph_color 0xff48aa2a
# sketchybar -m set cpu_sys label_padding_left 8
# sketchybar -m set cpu_sys icon_padding_left 8
# sketchybar -m set cpu_sys associated_space 1
# sketchybar -m set cpu_sys update_freq 5
# sketchybar -m set cpu_sys icon 

# Network graph
# sketchybar -m add component graph network_down right 150 nospace
# sketchybar -m set network_down associated_space 2
# sketchybar -m set network_down associated_space 4
# sketchybar -m set network_down icon ⮁
# sketchybar -m set network_down label_padding_left 8
# sketchybar -m set network_down icon_padding_left 8
# sketchybar -m set network_down update_freq 5
# sketchybar -m set network_down graph_color 0xffffffff
# sketchybar -m set network_down script "~/.config/sketchybar/plugins/network_graph.sh"
#
# sketchybar -m add component graph network_up right 150
# sketchybar -m set network_up icon ⮁
# sketchybar -m set network_up label_padding_left 8
# sketchybar -m set network_up icon_padding_left 8
# sketchybar -m set network_up associated_space 2
# sketchybar -m set network_up update_freq 5
# sketchybar -m set network_up associated_space 4
# sketchybar -m set network_up graph_color 0xff48aa2a

# sketchybar -m add item topproc right
# sketchybar -m set topproc script "~/.config/sketchybar/plugins/topproc.sh"
# sketchybar -m set topproc update_freq 15

###################### CENTER ITEMS ###################
# Spotify
sketchybar -m --add event spotify_change "com.spotify.client.PlaybackStateChanged" \
              --add item spotifyIndicator center \
              --set spotifyIndicator script="~/.config/sketchybar/plugins/spotifyIndicator.sh" \
              --set spotifyIndicator click_script="osascript -e 'tell application \"Spotify\" to pause'" \
              --subscribe spotifyIndicator spotify_change

sketchybar -m --update

echo "sketchybar: configuration loaded"
echo "sketchybar: loading colors..."
source ~/.config/sketchybar/sketchybarcolors
