import = ["/home/carson/.cache/wal/colors-alacritty.toml"]
live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[cursor]
blink_interval = 400
unfocused_hollow = true

[cursor.style]
blinking = "always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[font.italic]
family = "Terminus"
style = "Italic"

[font.normal]
family = "Terminus"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "P"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "N"
mods = "Shift|Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 5
y = 5
